### ISSUE TITLE
Missing inverter for gate input to RS flip flop

### ISSUE THREAD

**Issue by daglem** [libsidplayfp/SID_schematics#2]
Working on https://github.com/daglem/reDIP-SID, I noticed a small error in the schematic for the envelope counter.

See the attached image for where I believe the gate signal should be inverted.

![env_dac_cnt_ctl](https://user-images.githubusercontent.com/22003725/210890369-500a338e-9fb2-4aa8-86ca-dad3907049de.png)

**Comment by drfiemost** [comment]
Ah yes, you're right! There are some errors in the schematics as stated in [this post](http://forum.6502.org/viewtopic.php?f=8&t=4150&start=150&sid=04667f2e6577a8967d2b649537040ca3&sid=04667f2e6577a8967d2b649537040ca3#p57796)

This is the correct version:
![Counting direction circuit](http://forum.6502.org/download/file.php?id=5817&mode=view)

And this is the corresponding transistor schematics:
![Counting direction transistor schematic](https://raw.githubusercontent.com/wiki/libsidplayfp/SID_schematics/images/Counting_direction.png)
